export const ITEMS_ACTION_TYPES = {
  FETCH_ITEMS_START: 'ITEMS/FETCH_ITEMS_START',
  FETCH_ITEMS_SUCCESS: 'ITEMS/FETCH_ITEMS_SUCCESS',
  FETCH_ITEMS_FAILED: 'ITEMS/FETCH_ITEMS_FAILED',
  POST_ITEM_START: 'ITEMS/POST_ITEM_START',
  POST_ITEM_FAILED: 'ITEMS/POST_ITEM_FAILED',
  POST_ITEM_SUCCESS: 'ITEMS/POST_ITEM_SUCCESS',
  DELETE_ITEM_START: 'ITEMS/DELETE_ITEM_START',
  DELETE_ITEM_FAILED: 'ITEMS/DELETE_ITEM_FAILED',
  DELETE_ITEM_SUCCESS: 'ITEMS/DELETE_ITEM_SUCCESS',
};